steps:
- task: DockerLogin@0
  displayName: 'Login to docker environment'
  script: docker login -u $(dockerId) -p $(pswd) palisadeacr.azurecr.io

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: '$(System.TeamProjectId)'
    pipeline: 8
    specificBuildWithTriggering: true
    artifactName: local-docker
    downloadPath: '$(System.DefaultWorkingDirectory)/example/deployment/'

- task: Docker@0
  displayName: 'Build  ${{ parameters.imageName }} image'
  inputs:
    azureSubscription: '${{variables.devOpsServiceConnection}}'
    azureContainerRegistry: 'palisadeacr.azurecr.io'
    dockerFile: '$(System.DefaultWorkingDirectory)/example/deployment/local-docker/example-docker-services/${{ parameters.imageName }}/Dockerfile'
    imageName: '${{ parameters.imageName }}:$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push ${{ parameters.imageName }} image'
  inputs:
    azureSubscription: '${{variables.devOpsServiceConnection}}'
    azureContainerRegistry: 'palisadeacr.azurecr.io'
    action: 'Push an image'
    imageName: '${{ parameters.imageName }}:$(Build.BuildId)'
    includeLatestTag: true
