steps:

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifacts'
  inputs:
    buildType: specific
    project: '$(System.TeamProjectId)'
    pipeline: 8
    specificBuildWithTriggering: true
    artifactName: local-docker
    downloadPath: '$(System.DefaultWorkingDirectory)/example/deployment/'

- script: docker build -t $(palisadeacr).azurecr.io/${{ parameters.imageName }}:$(Build.BuildId) $(System.DefaultWorkingDirectory)/example/deployment/local-docker/example-docker-services/${{ parameters.imageName }}
  displayName: 'Building ${{ parameters.imageName }} image'


- script: docker login -u $(palisadeacr) -p $(pswd) $(palisadeacr).azurecr.io && docker images && docker push '$(palisadeacr).azurecr.io/${{ parameters.imageName }}:$(Build.BuildId)'
  displayName: 'Pushing ${{ parameters.imageName }} image'
